### PR TITLE
Add other stacks as options

### PR DESCRIPTION
**Pull request by romainx**
Hello,

Added the possibility to select other stacks as an option.
Is also a way to test if the CI is OK for PR 😄 .

Best

### CODE REVIEW

**Review by mathbunnyru — COMMENTED** [review]
Do we need to add configs here as well?
https://github.com/jupyter/cookiecutter-docker-stacks/tree/master/configs

**Comment by romainx** [comment]
@mathbunnyru in fact they are never used, the key `stack_base_image` is directly used instead.

```jinja
FROM {{ cookiecutter.stack_base_image }}
```

We could do something like

- `stack_base_image` : `base-notebook`
- `stack_base`: 'jupyter/base-notebook'

However I don't think it's worth doing it if we have no other image related settings to define.

What do you think, should we delete them or use them as I explained and so create additional files for the other stacks?

**Comment by mathbunnyru** [comment]
I would just delete them. But we need to make sure documentation stays up-to-date.

**Comment by romainx** [comment]
Thanks, which documentation?

**Comment by mathbunnyru** [comment]
> Thanks, which documentation?

https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html#creating-a-project

We might need to update this documentation, if we remove configs folder.

**Comment by romainx** [comment]
@mathbunnyru maybe it's useless to do all this. I wanted to test the new CI on this repo itself, and it works (the check has passed). So I'm closing this PR as is. Thanks for your comments and help.
See you :-)

**Pull request closed without merging**
