### PR TITLE
Fix missing dependency in GH workflow template

### PR DESCRIPTION
**Pull request by hakamine**
Add missing dependency (six) to prevent error in GH actions.

### CODE REVIEW

**Comment by hakamine** [comment]
This PR fixes an error that occurs in the "Run tests" step of the GitHub workflow:

> Run python -m pytest tests
  python -m pytest tests
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.10/x64/lib
ImportError while loading conftest '/home/runner/work/tensorflow-d2l-notebook/tensorflow-d2l-notebook/tests/conftest.py'.
tests/conftest.py:3: in <module>
    import docker
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/docker/__init__.py:2: in <module>
    from .api import APIClient
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/docker/api/__init__.py:2: in <module>
    from .client import APIClient
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/docker/api/client.py:10: in <module>
    from .. import auth
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/docker/auth.py:5: in <module>
    import six
E   ModuleNotFoundError: No module named 'six'
Error: Process completed with exit code 4.

**Review by romainx — CHANGES_REQUESTED** [review]
Hello @hakamine,

Thanks for reporting that. In fact the origin of this issue seems to be due to an undeclared dependency of the `docker` Python package -> https://github.com/docker/docker-py/issues/2842.
We should not have to declare `six` since it is not a direct dependency of our tests.
However we could provide a workaround in the meantime.

I suggest to put it instead in `requirements-test.txt`.

```diff
docker
+ # workaround to fix https://github.com/docker/docker-py/issues/2842
+ six
pytest
requests
```

Could you please perform this change?

Many thanks

**Review by mathbunnyru — COMMENTED** [review]
I do fully agree with @romainx.

**Comment by hakamine** [comment]
Thank you @romainx. Changed as suggested.

**Review by romainx — APPROVED** [review]
LGTM

**Comment by romainx** [comment]
@hakamine merged thanks!

**Pull request merged**
